name: CI/CD for Strapi Using GithubActions
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Upgrade npm
      run: npm install -g npm@latest

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          #set -e

          # Update the package list and install Node.js and npm
          sudo apt update
          sudo apt install -y nodejs npm
          sudo npm install -g pm2

          # Define project directory
          PROJECT_DIR="/home/ubuntu/Strapi-CICD"

           # Remove the existing directory if it exists to avoid conflicts
            if [ -d "$PROJECT_DIR" ]; then
              rm -rf "$PROJECT_DIR"
            fi

          # Clone the Strapi repository
          git clone https://github.com/haripriya2413/Strapi-CICD
          cd Strapi-CICD
          # Install Strapi globally
          sudo npm install strapi@beta -g

          # Create a new Strapi project
          strapi new priya-project --dbclient=sqlite

          # Navigate to the new project directory
          cd priya-project

          # Start the Strapi application using pm2
          pm2 restart npm --name "strapi" -- run develop
